[general]

#import = [""]
live_config_reload = true
ipc_socket = true

[env]

WINIT_X11_SCALE_FACTOR = "1.0"

[window]

padding = { x = 20, y = 20 }
dynamic_padding = true

opacity = 0.9
blur = false
title = "Alacritty"

[font]

size = 9
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Propo", style = "Bold Italic" }

#offset = { x = , y =  }

builtin_box_drawing = true
